-- =====================================================================
-- V1: esquema inicial de PharmaBackend (Oracle)
--
-- Tipos elegidos para coincidir con lo que Hibernate 7 (OracleDialect)
-- genera a partir de las entidades, de modo que ddl-auto=validate pase:
--   Long          -> number(19,0)
--   Integer       -> number(10,0)
--   Boolean       -> boolean            (Oracle 23ai; ver nota abajo)
--   BigDecimal    -> number(p,s)
--   LocalDateTime -> timestamp(6)
--   String(n)     -> varchar2(n char)
--
-- Nota: en Oracle 21c o anterior no existe el tipo boolean; en ese caso
-- reemplazar por number(1,0) con check (col in (0,1)).
-- =====================================================================

create table categorias (
    id                 number(19,0) generated by default as identity,
    nombre             varchar2(50 char)  not null,
    descripcion        varchar2(200 char),
    estado             boolean            not null,
    fecha_creacion     timestamp(6)       not null,
    fecha_modificacion timestamp(6),
    constraint pk_categorias primary key (id)
);

create unique index ux_categorias_nombre on categorias (upper(nombre));

create table clientes (
    id                 number(19,0) generated by default as identity,
    dni                varchar2(8 char)   not null,
    nombres            varchar2(100 char) not null,
    apellidos          varchar2(100 char) not null,
    email              varchar2(150 char) not null,
    telefono           varchar2(15 char),
    direccion          varchar2(250 char),
    estado             boolean            not null,
    fecha_creacion     timestamp(6)       not null,
    fecha_modificacion timestamp(6),
    constraint pk_clientes primary key (id),
    constraint ux_clientes_dni unique (dni)
);

create unique index ux_clientes_email on clientes (upper(email));

create table productos (
    id                 number(19,0) generated by default as identity,
    nombre             varchar2(150 char) not null,
    precio             number(10,2)       not null,
    stock              number(10,0)       not null,
    estado             boolean            not null,
    categoria_id       number(19,0)       not null,
    fecha_creacion     timestamp(6)       not null,
    fecha_modificacion timestamp(6),
    constraint pk_productos primary key (id),
    constraint fk_productos_categoria
        foreign key (categoria_id) references categorias (id),
    constraint ck_productos_stock check (stock >= 0)
);

create unique index ux_productos_nombre on productos (upper(nombre));
create index ix_productos_categoria on productos (categoria_id);

create table ventas (
    id         number(19,0) generated by default as identity,
    fecha      timestamp(6)      not null,
    total      number(12,2)      not null,
    estado     varchar2(20 char) not null,
    cliente_id number(19,0)      not null,
    constraint pk_ventas primary key (id),
    constraint fk_ventas_cliente
        foreign key (cliente_id) references clientes (id),
    constraint ck_ventas_estado
        check (estado in ('REGISTRADA', 'ANULADA'))
);

create index ix_ventas_cliente on ventas (cliente_id);
create index ix_ventas_fecha   on ventas (fecha);

create table detalle_ventas (
    id          number(19,0) generated by default as identity,
    venta_id    number(19,0) not null,
    producto_id number(19,0) not null,
    cantidad    number(10,0) not null,
    precio      number(10,2) not null,
    subtotal    number(12,2) not null,
    constraint pk_detalle_ventas primary key (id),
    constraint fk_detalle_ventas_venta
        foreign key (venta_id) references ventas (id),
    constraint fk_detalle_ventas_producto
        foreign key (producto_id) references productos (id),
    constraint ck_detalle_ventas_cantidad check (cantidad > 0)
);

create index ix_detalle_ventas_venta    on detalle_ventas (venta_id);
create index ix_detalle_ventas_producto on detalle_ventas (producto_id);
